# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tmva/tmva/test/envelope
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/envelope
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-tmva-tmva-test-envelope-TMVA-Envelope]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/envelope/TMVA-Envelope" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/envelope" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-envelope-TMVA-Envelope]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/envelope/CMakeLists.txt;11;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/envelope/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-envelope-TMVA-Classification]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/envelope/TMVA-Classification" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/envelope" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-envelope-TMVA-Classification]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/envelope/CMakeLists.txt;12;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/envelope/CMakeLists.txt;0;")
