# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/net/netxng/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/net/netxng/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-net-netxng-test-RRawFileNetXNG]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/net/netxng/test/RRawFileNetXNG" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/net/netxng/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-net-netxng-test-RRawFileNetXNG]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/net/netxng/test/CMakeLists.txt;1;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/net/netxng/test/CMakeLists.txt;0;")
add_test([=[gtest-net-netxng-test-TNetXNGFileTest]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/net/netxng/test/TNetXNGFileTest" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/net/netxng/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-net-netxng-test-TNetXNGFileTest]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/net/netxng/test/CMakeLists.txt;3;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/net/netxng/test/CMakeLists.txt;0;")
