# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/hist/histdrawv7/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/hist/histdrawv7/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-hist-histdrawv7-test-drawUnit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/hist/histdrawv7/test/drawUnit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/hist/histdrawv7/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-hist-histdrawv7-test-drawUnit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/hist/histdrawv7/test/CMakeLists.txt;7;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/hist/histdrawv7/test/CMakeLists.txt;0;")
add_test([=[gtest-hist-histdrawv7-test-ioUnit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/hist/histdrawv7/test/ioUnit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/hist/histdrawv7/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-hist-histdrawv7-test-ioUnit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/hist/histdrawv7/test/CMakeLists.txt;12;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/hist/histdrawv7/test/CMakeLists.txt;0;")
