# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/core/foundation/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/core/foundation/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-core-foundation-test-testMake-unique]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testMake_unique" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testMake-unique]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;7;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-testTypeTraits]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testTypeTraits" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testTypeTraits]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;8;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-testNotFn]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testNotFn" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testNotFn]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;9;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-testClassEdit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testClassEdit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testClassEdit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;10;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-testLogger]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testLogger" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testLogger]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;11;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-testRRangeCast]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testRRangeCast" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testRRangeCast]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;12;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-testStringUtils]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/testStringUtils" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-testStringUtils]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;13;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
add_test([=[gtest-core-foundation-test-FoundationUtilsTests]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test/FoundationUtilsTests" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/foundation/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-foundation-test-FoundationUtilsTests]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;14;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/foundation/test/CMakeLists.txt;0;")
