# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/roofit/roostats/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-roofit-roostats-test-testHypoTestInvResult]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test/testHypoTestInvResult" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-DCOPY=/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/testHypoTestInvResult_1.root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roostats-test-testHypoTestInvResult]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;1;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roostats-test-testSPlot]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test/testSPlot" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roostats-test-testSPlot]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;4;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;0;")
add_test([=[test-stressroostats-cpu]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test/stressRooStats^-b^cpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-stressroostats-cpu]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" FAIL_REGULAR_EXPRESSION "FAILED|Error in" LABELS "longtest" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;16;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;0;")
add_test([=[test-stressroostats-cpu-minuit2]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roostats/test/stressRooStats^-minim^Minuit2^-b^cpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-stressroostats-cpu-minuit2]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" FAIL_REGULAR_EXPRESSION "FAILED|Error in" LABELS "longtest" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;23;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roostats/test/CMakeLists.txt;0;")
