# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[TMVA-DNN-CNN-Im2Col-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testIm2ColCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-Im2Col-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;116;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-PoolingLayer-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testPoolingLayerCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-PoolingLayer-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;119;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-ConvLayer-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testConvLayerCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-ConvLayer-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;122;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-RotWeights-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testRotWeightsCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-RotWeights-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;125;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-Forward-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testForwardPassCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-Forward-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;128;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-Loss-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testConvNetLossCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-Loss-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;131;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-Pred-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testConvNetPredCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-Pred-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;134;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-Reshape-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testReshapeCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-Reshape-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;137;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-Backpropagation-CPU]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testConvBackpropagationCpu" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-Backpropagation-CPU]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;147;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
add_test([=[TMVA-DNN-CNN-MethodDL]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/DNN/CNN/testMethodDLCNN" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-DNN-CNN-MethodDL]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;150;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/DNN/CNN/CMakeLists.txt;0;")
