# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/math/matrix/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/math/matrix/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-math-matrix-test-testMatrixTSparse]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/matrix/test/testMatrixTSparse" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/math/matrix/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-math-matrix-test-testMatrixTSparse]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/matrix/test/CMakeLists.txt;7;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/math/matrix/test/CMakeLists.txt;0;")
add_test([=[gtest-math-matrix-test-testMatrixTDecomp]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/matrix/test/testMatrixTDecomp" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/math/matrix/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-math-matrix-test-testMatrixTDecomp]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/matrix/test/CMakeLists.txt;8;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/math/matrix/test/CMakeLists.txt;0;")
