# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/core/meta/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/core/meta/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-core-meta-test-testStatusBitsChecker]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test/testStatusBitsChecker" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-meta-test-testStatusBitsChecker]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;7;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;0;")
add_test([=[gtest-core-meta-test-testHashRecursiveRemove]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test/testHashRecursiveRemove" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-meta-test-testHashRecursiveRemove]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;8;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;0;")
add_test([=[gtest-core-meta-test-testTClass]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test/testTClass" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-meta-test-testTClass]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;9;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;0;")
add_test([=[gtest-core-meta-test-testTDataType]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test/testTDataType" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-meta-test-testTDataType]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;10;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;0;")
add_test([=[gtest-core-meta-test-testTEnum]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test/testTEnum" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/meta/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-meta-test-testTEnum]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;11;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/meta/test/CMakeLists.txt;0;")
