# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/io/io/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/io/io/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-io-io-test-RRawFile]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/RRawFile" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-RRawFile]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;7;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
add_test([=[gtest-io-io-test-TFile]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/TFile" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-TFile]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;8;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
add_test([=[gtest-io-io-test-TBufferFile]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/TBufferFile" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-TBufferFile]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;9;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
add_test([=[gtest-io-io-test-TBufferMerger]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/TBufferMerger" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-TBufferMerger]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;10;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
add_test([=[gtest-io-io-test-TBufferJSON]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/TBufferJSON" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-TBufferJSON]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;11;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
add_test([=[gtest-io-io-test-TFileMerger]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/TFileMerger" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-TFileMerger]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;12;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
add_test([=[gtest-io-io-test-TROMemFile]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test/TROMemFile" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/io/io/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-io-io-test-TROMemFile]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;13;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/io/io/test/CMakeLists.txt;0;")
