# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tree/ntupleutil/v7/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tree/ntupleutil/v7/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-tree-ntupleutil-v7-test-ntuple-importer]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tree/ntupleutil/v7/test/ntuple_importer" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tree/ntupleutil/v7/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tree-ntupleutil-v7-test-ntuple-importer]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tree/ntupleutil/v7/test/CMakeLists.txt;22;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tree/ntupleutil/v7/test/CMakeLists.txt;0;")
add_test([=[gtest-tree-ntupleutil-v7-test-ntuple-inspector]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tree/ntupleutil/v7/test/ntuple_inspector" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tree/ntupleutil/v7/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tree-ntupleutil-v7-test-ntuple-inspector]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tree/ntupleutil/v7/test/CMakeLists.txt;23;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tree/ntupleutil/v7/test/CMakeLists.txt;0;")
