# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/bindings/experimental/distrdf/test/backend
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pyunittests-distrdf-unit-backend-test-common]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/opt/anaconda3/bin/python3.11^-B^-m^unittest^discover^-s^/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/^-p^test_common.py^-v" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-DENV=ROOTSYS=/Users/abhiacherjee/Documents/rootbench/root#PATH=/Users/abhiacherjee/Documents/rootbench/root/bin:/usr/local/bin:/Users/abhiacherjee/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Users/abhiacherjee/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin#LD_LIBRARY_PATH=/Users/abhiacherjee/Documents/rootbench/root/lib:#PYTHONPATH=/Users/abhiacherjee/Documents/rootbench/root/lib:" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[pyunittests-distrdf-unit-backend-test-common]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1941;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/CMakeLists.txt;18;ROOT_ADD_PYUNITTEST;/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/CMakeLists.txt;0;")
add_test([=[pyunittests-distrdf-unit-backend-test-dist]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/opt/anaconda3/bin/python3.11^-B^-m^unittest^discover^-s^/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/^-p^test_dist.py^-v" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-DENV=ROOTSYS=/Users/abhiacherjee/Documents/rootbench/root#PATH=/Users/abhiacherjee/Documents/rootbench/root/bin:/usr/local/bin:/Users/abhiacherjee/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Users/abhiacherjee/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin#LD_LIBRARY_PATH=/Users/abhiacherjee/Documents/rootbench/root/lib:#PYTHONPATH=/Users/abhiacherjee/Documents/rootbench/root/lib:" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[pyunittests-distrdf-unit-backend-test-dist]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1941;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/CMakeLists.txt;19;ROOT_ADD_PYUNITTEST;/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/CMakeLists.txt;0;")
add_test([=[pyunittests-distrdf-unit-backend-test-graph-caching]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/opt/anaconda3/bin/python3.11^-B^-m^unittest^discover^-s^/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/^-p^test_graph_caching.py^-v" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-DENV=ROOTSYS=/Users/abhiacherjee/Documents/rootbench/root#PATH=/Users/abhiacherjee/Documents/rootbench/root/bin:/usr/local/bin:/Users/abhiacherjee/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Users/abhiacherjee/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin#LD_LIBRARY_PATH=/Users/abhiacherjee/Documents/rootbench/root/lib:#PYTHONPATH=/Users/abhiacherjee/Documents/rootbench/root/lib:" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[pyunittests-distrdf-unit-backend-test-graph-caching]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1941;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/CMakeLists.txt;20;ROOT_ADD_PYUNITTEST;/Users/abhiacherjee/Documents/root_src/bindings/experimental/distrdf/test/backend/CMakeLists.txt;0;")
