# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-tmva-tmva-test-crossvalidation-testCrossValidationSplitting]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation/testCrossValidationSplitting" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-crossvalidation-testCrossValidationSplitting]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;15;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-crossvalidation-testCrossValidationIntVar]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation/testCrossValidationIntVar" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-crossvalidation-testCrossValidationIntVar]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;19;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-crossvalidation-testCrossValidationMultiProc]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation/testCrossValidationMultiProc" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-crossvalidation-testCrossValidationMultiProc]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;25;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;0;")
add_test([=[TMVA-CrossValidation-Serialise]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/crossvalidation/testCrossValidationSerialise" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[TMVA-CrossValidation-Serialise]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;34;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/crossvalidation/CMakeLists.txt;0;")
