# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/core/cont/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/core/cont/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-core-cont-test-coreconttestUnit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test/coreconttestUnit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-cont-test-coreconttestUnit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1808;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;7;ROOT_ADD_UNITTEST_DIR;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;0;")
add_test([=[gtest-core-cont-test-testTypedIteration]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test/testTypedIteration" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-cont-test-testTypedIteration]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;9;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;0;")
add_test([=[gtest-core-cont-test-TSeqTests]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test/TSeqTests" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-cont-test-TSeqTests]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;10;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;0;")
add_test([=[gtest-core-cont-test-testIter]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test/testIter" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/cont/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-cont-test-testIter]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;11;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/cont/test/CMakeLists.txt;0;")
