# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/core/thread/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/core/thread/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-core-thread-test-corethreadtestUnit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/thread/test/corethreadtestUnit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/thread/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-thread-test-corethreadtestUnit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1808;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/thread/test/CMakeLists.txt;10;ROOT_ADD_UNITTEST_DIR;/Users/abhiacherjee/Documents/root_src/core/thread/test/CMakeLists.txt;0;")
add_test([=[gtest-core-thread-test-testTThreadedObject]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/thread/test/testTThreadedObject" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/thread/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-thread-test-testTThreadedObject]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/thread/test/CMakeLists.txt;13;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/thread/test/CMakeLists.txt;0;")
add_test([=[gtest-core-thread-test-testInterpreterLock]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/core/thread/test/testInterpreterLock^--gtest_repeat=50^--gtest_break_on_failure" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/core/thread/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-core-thread-test-testInterpreterLock]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/core/thread/test/CMakeLists.txt;16;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/core/thread/test/CMakeLists.txt;0;")
