# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tmva/tmva/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-tmva-tmva-test-TestRandomGenerator]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/TestRandomGenerator" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-TestRandomGenerator]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;13;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-TestOptimizeConfigParameters]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/TestOptimizeConfigParameters" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-TestOptimizeConfigParameters]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;16;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-rtensor]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/rtensor" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-rtensor]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;22;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-rtensor-iterator]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/rtensor-iterator" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-rtensor-iterator]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;23;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-rtensor-utils]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/rtensor-utils" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-rtensor-utils]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;24;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-rstandardscaler]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/rstandardscaler" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-rstandardscaler]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;26;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-rreader]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/rreader" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-rreader]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;28;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-branchlessForest]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/branchlessForest" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-branchlessForest]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;31;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[gtest-tmva-tmva-test-rbdt]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/rbdt" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tmva-tmva-test-rbdt]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;32;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
add_test([=[test-stresstmva]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/tmva/test/stressTMVA^-b" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-stresstmva]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" LABELS "longtest" TIMEOUT "1800" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;55;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/tmva/test/CMakeLists.txt;0;")
