# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/roofit/hs3/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/roofit/hs3/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-roofit-hs3-test-testRooFitHS3]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/hs3/test/testRooFitHS3" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/hs3/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-hs3-test-testRooFitHS3]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/hs3/test/CMakeLists.txt;1;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/hs3/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-hs3-test-testHS3SimultaneousFit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/hs3/test/testHS3SimultaneousFit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/hs3/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-hs3-test-testHS3SimultaneousFit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/hs3/test/CMakeLists.txt;2;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/hs3/test/CMakeLists.txt;0;")
