# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tmva/pymva/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[PyMVA-RandomForest-Classification]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test/testPyRandomForestClassification" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[PyMVA-RandomForest-Classification]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;28;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;0;")
add_test([=[PyMVA-RandomForest-Multiclass]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test/testPyRandomForestMulticlass" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[PyMVA-RandomForest-Multiclass]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;33;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;0;")
add_test([=[PyMVA-GTB-Classification]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test/testPyGTBClassification" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[PyMVA-GTB-Classification]=] PROPERTIES  DEPENDS "PyMVA-RandomForest-Classification" ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;38;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;0;")
add_test([=[PyMVA-GTB-Multiclass]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test/testPyGTBMulticlass" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[PyMVA-GTB-Multiclass]=] PROPERTIES  DEPENDS "PyMVA-RandomForest-Multiclass" ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;43;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;0;")
add_test([=[PyMVA-AdaBoost-Classification]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test/testPyAdaBoostClassification" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[PyMVA-AdaBoost-Classification]=] PROPERTIES  DEPENDS "PyMVA-GTB-Classification" ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;48;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;0;")
add_test([=[PyMVA-AdaBoost-Multiclass]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tmva/pymva/test/testPyAdaBoostMulticlass" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[PyMVA-AdaBoost-Multiclass]=] PROPERTIES  DEPENDS "PyMVA-GTB-Multiclass" ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;53;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tmva/pymva/test/CMakeLists.txt;0;")
