# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/roofit/roofit/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-roofit-roofit-test-testRooBernstein]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooBernstein" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooBernstein]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;9;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooBifurGauss]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooBifurGauss" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooBifurGauss]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;10;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooCrystalBall]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooCrystalBall" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooCrystalBall]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;11;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooExponential]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooExponential" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-DCOPY=/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/exponentialPdf.root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooExponential]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;12;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooGaussian]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooGaussian" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooGaussian]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;15;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooJohnson]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooJohnson" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooJohnson]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;16;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooKeysPdf]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooKeysPdf" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooKeysPdf]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;17;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooLandau]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooLandau" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooLandau]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;18;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooParamHistFunc]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooParamHistFunc" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooParamHistFunc]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;19;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
add_test([=[gtest-roofit-roofit-test-testRooPoisson]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test/testRooPoisson" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/roofit/roofit/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-roofit-roofit-test-testRooPoisson]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;20;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/roofit/roofit/test/CMakeLists.txt;0;")
