# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/tree/treeplayer/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gtest-tree-treeplayer-test-treetreeplayertestUnit]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test/treetreeplayertestUnit" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tree-treeplayer-test-treetreeplayertestUnit]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1808;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tree/treeplayer/test/CMakeLists.txt;8;ROOT_ADD_UNITTEST_DIR;/Users/abhiacherjee/Documents/root_src/tree/treeplayer/test/CMakeLists.txt;0;")
add_test([=[gtest-tree-treeplayer-test-treeprocessormt]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test/treeprocessormt" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tree-treeplayer-test-treeprocessormt]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tree/treeplayer/test/CMakeLists.txt;14;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tree/treeplayer/test/CMakeLists.txt;0;")
add_test([=[gtest-tree-treeplayer-test-treeprocessormt-remotefiles]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test/treeprocessormt_remotefiles" "-DCWD=/Users/abhiacherjee/Documents/rootbench/root/tree/treeplayer/test" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[gtest-tree-treeplayer-test-treeprocessormt-remotefiles]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/rootbench/root/RootMacros.cmake;1863;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/tree/treeplayer/test/CMakeLists.txt;16;ROOT_ADD_GTEST;/Users/abhiacherjee/Documents/root_src/tree/treeplayer/test/CMakeLists.txt;0;")
