# CMake generated Testfile for 
# Source directory: /Users/abhiacherjee/Documents/root_src/math/genvector/test
# Build directory: /Users/abhiacherjee/Documents/rootbench/root/math/genvector/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test-genvector-rotationApplication]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/genvector/test/rotationApplication" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-genvector-rotationApplication]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;10;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;0;")
add_test([=[test-genvector-boost]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/genvector/test/boost" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-genvector-boost]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;13;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;0;")
add_test([=[test-genvector-genvector]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/genvector/test/testGenvector" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-genvector-genvector]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;16;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;0;")
add_test([=[test-genvector-vectorio]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/genvector/test/testVectorIO" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-DCOPY=/Users/abhiacherjee/Documents/root_src/math/genvector/test/Track.h" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-genvector-vectorio]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;19;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;0;")
add_test([=[test-genvector-coordinates3D]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/genvector/test/coordinates3D" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-genvector-coordinates3D]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;23;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;0;")
add_test([=[test-genvector-coordinates4D]=] "/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake" "-DCMD=/Users/abhiacherjee/Documents/rootbench/root/math/genvector/test/coordinates4D" "-DSYS=/Users/abhiacherjee/Documents/rootbench/root" "-P" "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootTestDriver.cmake")
set_tests_properties([=[test-genvector-coordinates4D]=] PROPERTIES  ENVIRONMENT "ROOT_HIST=0" _BACKTRACE_TRIPLES "/Users/abhiacherjee/Documents/root_src/cmake/modules/RootMacros.cmake;1696;add_test;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;26;ROOT_ADD_TEST;/Users/abhiacherjee/Documents/root_src/math/genvector/test/CMakeLists.txt;0;")
