name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true

    - name: Conda info
      shell: bash -l {0}
      run: conda info

    - name: "Init conda"
      shell: bash -l {0}
      run: |
          conda init bash

    - name: Conda install dependencies
      shell: bash -l {0}
      run: |
           conda create -n rootbench -y -c conda-forge root cmake pytest pytest-benchmark pytest-csv numpy numba onnx

    - name: Configure and build
      shell: bash -l {0}
      run: |
           conda activate rootbench
           mkdir -p build && cd build
           cmake -Dcuda=OFF ..
           cmake --build . -j $(nproc)

    - name: Run benchmarks
      shell: bash -l {0}
      run: |
           conda activate rootbench
           export RB_TEMP_FS=.
           cd build
           ctest -V
